#!/usr/bin/env bash
#
# verify_reference_pins.sh - Enforce the identity of the vendored upstream trees
# (audit U-10 / A-09, "CI hash-pinning" remainder; S37).
#
# WHY THIS EXISTS: U-10's provenance half was "verified" by hand in S11 - a
# fresh clone, a diff, per-file hashes written into
# reference_code/REFERENCE_MANIFEST.md - and then nothing watched the trees
# again. The row's own missing item was exactly that: CI hash-pinning. Running
# this at the time would have caught two things the prose got wrong (both
# measured in S37, see REFERENCE_MANIFEST.md):
#
#   1. `src/Makefile.w32` is NOT upstream-identical. It carries a local
#      functional edit (kcolor.obj added to GIFSICLE_OBJS and GIFDIFF_OBJS,
#      upstream's own .w32 makefile is missing it). The S11 manifest recorded a
#      hash for that file which is, verifiably, today's file put back to CRLF -
#      so the edit was already there in S11 and the "identical in every shared
#      file" sentence was simply wrong.
#   2. Both trees are LF where upstream is CRLF in the two Windows makefiles -
#      a consequence of the 2026-09-22 repo re-creation coming back through a
#      web upload. Byte-exactness therefore has to be claimed modulo those two
#      files, and stated as such.
#
# WHAT IT CHECKS: every file of the three pinned sets, by sha256, against
# reference_code/REFERENCE_PINS.txt - plus the absence of unexpected extra
# files (an added file is drift too) and the presence of every pinned path (a
# deletion is drift). Failures name the file, its recorded hash and its actual
# hash, so the fix is a review, not a re-derivation.
#
# RE-PINNING (deliberate, reviewable): `./scripts/verify_reference_pins.sh --emit`
# rewrites the pins file from the on-disk bytes. Do that ONLY when the change is
# intended, and say why in the commit message - the pins are the record, this
# script is the enforcement.
#
# Usage:
#   ./scripts/verify_reference_pins.sh          # verify; exit 1 on any drift
#   ./scripts/verify_reference_pins.sh --emit   # re-pin (writes REFERENCE_PINS.txt)
#   ./scripts/verify_reference_pins.sh --list   # print the current file sets

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
PINS="$REPO_ROOT/reference_code/REFERENCE_PINS.txt"

# The pinned sets. Every set is a directory or file whose CONTENT is vendored
# upstream material (or the product-owned config staged into the upstream build),
# each with the upstream identity it is pinned against.
#   <label>|<path>|<upstream basis>
SETS=(
  "reference_code/gifsicle|$REPO_ROOT/reference_code/gifsicle|kohler/gifsicle @ 07f5c4c3de1306156e1d8f33e62971d4664c8f7d"
  "reference_code/gifsicle-nested-1.96|$REPO_ROOT/reference_code/gifsicle-nested-1.96|kohler/gifsicle @ v1.96 (a08e0f6686d467bb8b9e4715b1f1835f12984fb0)"
  "config.native.h|$REPO_ROOT/working_code/gifscythe/build_support/gifsicle/config.native.h|product-owned; staged as config.h by build_engine.sh"
)

MODE=verify
case "${1:-}" in
  --emit) MODE=emit ;;
  --list) MODE=list ;;
  "") ;;
  *) echo "usage: verify_reference_pins.sh [--emit|--list]" >&2; exit 2 ;;
esac

# Sorted "sha256  <set-label>/<relpath>" lines for every pinned set, exactly as
# they are written to the pins file. LC_ALL=C so the order is locale-independent
# (the same rule the S11 manifest's own reproduce command used).
current_facts() {
  local spec label path
  for spec in "${SETS[@]}"; do
    IFS='|' read -r label path _basis <<<"$spec"
    if [[ -f "$path" ]]; then
      printf '%s  %s\n' "$(sha256sum "$path" | cut -d' ' -f1)" "$label"
    elif [[ -d "$path" ]]; then
      (cd "$path" && find . -type f -print | sed 's|^\./||' | LC_ALL=C sort | while IFS= read -r f; do
        printf '%s  %s/%s\n' "$(sha256sum "$f" | cut -d' ' -f1)" "$label" "$f"
      done)
    else
      printf 'MISSING-PATH  %s\n' "$label"
    fi
  done
}

case "$MODE" in
  list)
    for spec in "${SETS[@]}"; do
      IFS='|' read -r label path basis <<<"$spec"
      n=$([[ -d "$path" ]] && find "$path" -type f | wc -l || echo 1)
      printf '%-38s %3s file(s)  %s\n' "$label" "$n" "$basis"
    done
    exit 0
    ;;
  emit)
    {
      printf '# Vendored upstream identity pins (audit U-10 / A-09).\n'
      printf '# Generated by working_code/gifscythe/scripts/verify_reference_pins.sh --emit.\n'
      printf '# Do not hand-edit: re-pin deliberately and say why in the commit message.\n'
      printf '# Format: <sha256>  <set>/<relpath>   (LC_ALL=C sort order)\n'
      for spec in "${SETS[@]}"; do
        IFS='|' read -r label path basis <<<"$spec"
        printf '#\n# set: %s\n# basis: %s\n' "$label" "$basis"
        current_facts | grep "  ${label}/" || true
        if [[ -f "$path" ]]; then current_facts | grep "  ${label}$" || true; fi
      done
    } >"$PINS.tmp"
    # current_facts walks every set per call; rebuild once, filter per section.
    {
      printf '# Vendored upstream identity pins (audit U-10 / A-09).\n'
      printf '# Generated by working_code/gifscythe/scripts/verify_reference_pins.sh --emit.\n'
      printf '# Do not hand-edit: re-pin deliberately and say why in the commit message.\n'
      printf '# Format: <sha256>  <set>/<relpath>   (LC_ALL=C sort order)\n'
      facts="$(current_facts)"
      for spec in "${SETS[@]}"; do
        IFS='|' read -r label path basis <<<"$spec"
        printf '#\n# set: %s\n# basis: %s\n' "$label" "$basis"
        printf '%s\n' "$facts" | grep -E "  ${label}(/|$)" || true
      done
    } >"$PINS.tmp"
    mv "$PINS.tmp" "$PINS"
    echo "wrote $PINS ($(grep -cv '^#' "$PINS") pinned file(s))"
    exit 0
    ;;
esac

if [[ ! -f "$PINS" ]]; then
  echo "FAIL: pins file missing ($PINS) - generate it with --emit" >&2
  exit 1
fi

fail=0
facts="$(current_facts)"
recorded="$(grep -v '^#' "$PINS" | grep -v '^[[:space:]]*$' | LC_ALL=C sort)"

# 1. Missing or changed files.
while IFS= read -r line; do
  [[ -z "$line" ]] && continue
  want="${line%%  *}"
  rel="${line#*  }"
  have="$(printf '%s\n' "$facts" | awk -v k="$rel" '$2==k {print $1}' | head -1)"
  if [[ -z "$have" ]]; then
    echo "FAIL: pinned file is gone: $rel" >&2
    fail=1
  elif [[ "$have" != "$want" ]]; then
    echo "FAIL: content drifted: $rel" >&2
    echo "        pinned: $want" >&2
    echo "        actual: $have" >&2
    fail=1
  fi
done <<<"$recorded"

# 2. Unexpected extras (a new file inside a vendored tree is drift too).
while IFS= read -r line; do
  [[ -z "$line" ]] && continue
  rel="${line#*  }"
  if ! printf '%s\n' "$recorded" | grep -qE "  ${rel//./\\.}$"; then
    echo "FAIL: unexpected file in a pinned set (not pinned, not upstream): $rel" >&2
    fail=1
  fi
done <<<"$facts"

if [[ "$fail" -ne 0 ]]; then
  echo "==> reference pins: FAIL - if the change is intended, re-pin deliberately" >&2
  exit 1
fi

echo "==> reference pins: OK ($(printf '%s\n' "$recorded" | grep -c . ) files across ${#SETS[@]} sets; no drift)"
